version: "3.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper_instance
    ports:
     - "2181:2181"
    networks:
      - kafka_network
  kafka:
    image: "wurstmeister/kafka:2.13-2.7.0"
    container_name: kafka_broker
    ports:
     - "9092:9092"
    expose:
     - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka_broker:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_instance:2181
      KAFKA_CREATE_TOPICS: "simple_topic:1:1,multiple_consumers_topic:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka_network
  jupyter:
    build: .
    container_name: jupyter_instance
    volumes:
      - type: bind
        source: ./notebooks/
        target: /home/jovyan/
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge